bài 3.1 Viết chương trình NumPy để:

Lấy phiên bản NumPy hiện tại

Hiển thị cấu hình xây dựng (build configuration) của NumPy

In [2]:
import numpy as np

# 1️⃣ In ra phiên bản NumPy hiện tại
print("Phiên bản NumPy:")
print(np.__version__)


# 2️⃣ Hiển thị cấu hình build của NumPy
print("Cấu hình xây dựng của NumPy:")
np.show_config()


Phiên bản NumPy:
2.2.4
Cấu hình xây dựng của NumPy:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-f6dmj7nt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-f6dmj7nt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-f6dmj7nt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-f6dmj7nt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-open

Bài 3.2
Yêu cầu tóm tắt

Tạo array arr có giá trị từ 0 → 9, in:

các phần tử

kiểu dữ liệu

kích thước

Từ arr → tạo:

arr_odd (số lẻ)

arr_even (số chẵn)

Từ arr → tạo arr_update_1:

số chẵn giữ nguyên

số lẻ thay bằng 100

In [4]:
import numpy as np

# =====================
# 1️⃣ Tạo array arr từ 0 đến 9
# =====================
arr = np.arange(10)

print("Array arr:")
print(arr)

print("Kiểu dữ liệu:", arr.dtype)
print("Kích thước:", arr.shape)



# =====================
# 2️⃣ Tạo arr_odd và arr_even
# =====================
arr_odd = arr[arr % 2 == 1]     # số lẻ
arr_even = arr[arr % 2 == 0]    # số chẵn

print("Array số lẻ (arr_odd):")
print(arr_odd)

print("Array số chẵn (arr_even):")
print(arr_even)

print("\n" + "="*40 + "\n")

# =====================
# 3️⃣ Tạo arr_update_1
#    - chẵn giữ nguyên
#    - lẻ -> 100
# =====================
arr_update_1 = arr.copy()       # copy để không làm thay đổi arr gốc
arr_update_1[arr_update_1 % 2 == 1] = 100

print("Array sau khi cập nhật (arr_update_1):")
print(arr_update_1)


Array arr:
[0 1 2 3 4 5 6 7 8 9]
Kiểu dữ liệu: int64
Kích thước: (10,)
Array số lẻ (arr_odd):
[1 3 5 7 9]
Array số chẵn (arr_even):
[0 2 4 6 8]


Array sau khi cập nhật (arr_update_1):
[  0 100   2 100   4 100   6 100   8 100]


bài 3.3

In [5]:
import numpy as np

# =====================
# Khởi tạo dữ liệu
# =====================
arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# =====================
# 1️⃣ arr_c: phần tử xuất hiện ở cả arr_a và arr_b
# =====================
arr_c = np.intersect1d(arr_a, arr_b)

print("arr_c (xuất hiện ở cả arr_a và arr_b):")
print(arr_c)

print("\n" + "="*40 + "\n")

# =====================
# 2️⃣ arr_d: phần tử chỉ xuất hiện ở arr_a
# =====================
arr_d = np.setdiff1d(arr_a, arr_b)

print("arr_d (chỉ xuất hiện ở arr_a):")
print(arr_d)

print("\n" + "="*40 + "\n")

# =====================
# 3️⃣ arr_f: giá trị từ 5 đến 10 trong arr_e
# =====================
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])

arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]

print("arr_f (giá trị từ 5 đến 10):")
print(arr_f)


arr_c (xuất hiện ở cả arr_a và arr_b):
[2 4]


arr_d (chỉ xuất hiện ở arr_a):
[1 3 5 6]


arr_f (giá trị từ 5 đến 10):
[ 6  9 10  8  6]


bài 3.4

In [10]:
import numpy as np

# =====================
# 1️⃣ arr_zeros: 10 số 0, vị trí thứ 5 = 1
# =====================
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[4] = 1   # vị trí thứ 5 có index = 4

print("arr_zeros:")
print(arr_zeros)

print("\n" + "="*40 + "\n")

# =====================
# 2️⃣ arr_h: từ 10 đến 24, đảo ngược
# =====================
arr_h = np.arange(10, 25)

print("arr_h đảo ngược:")
print(arr_h[::-1])

print("\n" + "="*40 + "\n")

# =====================
# 3️⃣ arr_l: phần tử khác 0
# =====================
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])

arr_l = arr_k[arr_k != 0]

print("arr_l (khác 0):")
print(arr_l)

print("\n" + "="*40 + "\n")

# =====================
# 4️⃣ Thêm 10 và 20 vào cuối arr_l
# =====================
arr_l = np.append(arr_l, [10, 20])

print("arr_l sau khi thêm 10 và 20:")
print(arr_l)

print("\n" + "="*40 + "\n")

# =====================
# 5️⃣ Thêm 100 vào index = 5
# =====================
arr_l = np.insert(arr_l, 5, 100)

print("arr_l sau khi thêm 100 tại index 5:")
print(arr_l)

print("\n" + "="*40 + "\n")

# =====================
# 6️⃣ Xóa phần tử tại index 0, 1, 2
# =====================
arr_l = np.delete(arr_l, [0, 1, 2])

print("arr_l sau khi xóa index 0,1,2:")
print(arr_l)


arr_zeros:
[0 0 0 0 1 0 0 0 0 0]


arr_h đảo ngược:
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


arr_l (khác 0):
[1 2 8 2 1 3 5]


arr_l sau khi thêm 10 và 20:
[ 1  2  8  2  1  3  5 10 20]


arr_l sau khi thêm 100 tại index 5:
[  1   2   8   2   1 100   3   5  10  20]


arr_l sau khi xóa index 0,1,2:
[  2   1 100   3   5  10  20]


luyện tập từ file csv


In [20]:
import numpy as np

# =============================
# Câu 1. Đọc dữ liệu từ file CSV
# =============================
data = np.genfromtxt(
    "data.csv",
    delimiter=",",
    dtype=None,
    encoding="utf-8",
    missing_values="",
    filling_values=np.nan
)
print(data)
# =============================
# Câu 2. Tách các cột dữ liệu
# =============================
student_id = data['f0']
province = data['f1']
year = data['f2']
population = data['f3'].astype(float)
income = data['f4'].astype(float)
cpi = data['f5'].astype(float)
unemployment_rate = data['f6'].astype(float)

# =============================
# Câu 3. Loại bỏ giá trị thiếu
# =============================
income_clean = income[~np.isnan(income)]
cpi_clean = cpi[~np.isnan(cpi)]
unemployment_clean = unemployment_rate[~np.isnan(unemployment_rate)]

# =============================
# Câu 4. Một số thống kê cơ bản
# =============================
print("Dân số lớn nhất:", np.max(population))
print("Thu nhập trung bình:", np.mean(income_clean))
print("CPI trung bình:", np.mean(cpi_clean))
print("Tỷ lệ thất nghiệp thấp nhất:", np.min(unemployment_clean))


[(24174600112, 'Hà Nội', 2019, 1375953,  44.05, 111.1 , 3.07)
 (24174600112, 'Hà Nội', 2020, 3895894,    nan, 101.59, 5.93)
 (24174600112, 'Hà Nội', 2021, 4948633, 100.62,  92.07, 4.25)
 (24174600112, 'TP.HCM', 2019, 6150017,  55.46, 106.28, 5.42)
 (24174600112, 'TP.HCM', 2020, 1102960,  69.31, 120.39, 5.52)
 (24174600112, 'TP.HCM', 2021, 6659125,  42.25, 110.92, 4.7 )
 (24174600112, 'Đà Nẵng', 2019, 2721861,    nan, 104.06, 4.92)
 (24174600112, 'Đà Nẵng', 2020, 6054480,  68.46, 126.18, 4.  )
 (24174600112, 'Đà Nẵng', 2021, 7298116,  98.2 , 108.65, 2.52)
 (24174600112, 'Hải Phòng', 2019, 7371142,    nan, 124.74,  nan)
 (24174600112, 'Hải Phòng', 2020, 6308767,  72.61,  99.7 , 3.11)
 (24174600112, 'Hải Phòng', 2021, 4301456,  51.74,  90.55, 1.25)
 (24174600112, 'Cần Thơ', 2019, 5149997,  39.63,    nan, 1.38)
 (24174600112, 'Cần Thơ', 2020, 6258856,  34.65, 100.81,  nan)
 (24174600112, 'Cần Thơ', 2021, 2201846,  81.23, 107.74, 2.41)]
Dân số lớn nhất: 7371142.0
Thu nhập trung bình: 63.184