In [5]:
import numpy as np
import sys

# Tạo danh sách Python với 1000 phần tử
S = list(range(1000))

# Đo kích thước của toàn bộ list (bao gồm overhead)
size_S = sys.getsizeof(S)
print("Kích thước của đối tượng List (overhead, không tính phần tử):", size_S, "bytes")

# Tính tổng kích thước list + phần tử
total_S_size = size_S + sum(sys.getsizeof(item) for item in S)
print("Tổng kích thước List (bao gồm phần tử):", total_S_size, "bytes")

# Tạo mảng NumPy với 1000 phần tử
D = np.arange(1000)

# Đo kích thước mỗi phần tử trong NumPy array
print("Kích thước mỗi phần tử trong mảng NumPy (bytes):", D.itemsize)

# Đo kích thước toàn bộ mảng NumPy
array_size = D.nbytes
print("Tổng kích thước của mảng NumPy:", array_size, "bytes")

# So sánh tỷ lệ sử dụng bộ nhớ
print(f"Tỷ lệ (List / NumPy array): {total_S_size / array_size:.2f}")


Kích thước của đối tượng List (overhead, không tính phần tử): 8056 bytes
Tổng kích thước List (bao gồm phần tử): 36056 bytes
Kích thước mỗi phần tử trong mảng NumPy (bytes): 8
Tổng kích thước của mảng NumPy: 8000 bytes
Tỷ lệ (List / NumPy array): 4.51


In [3]:
import numpy as np


In [6]:
import numpy as np

# Tạo mảng chứa 5 giá trị từ 0 đến 10 (gồm giá trị kết thúc)
arr_1 = np.linspace(0, 10, 5)
print(arr_1)
# Tạo mảng chứa 10 giá trị từ 0 đến 1 (không chứa giá trị kết thúc)
arr_2 = np.linspace(0, 1, 10, endpoint=False)
print(arr_2)
# Tạo mảng chứa 100 giá trị từ 1 đến 10 và trả về kích thước bước
arr_3, step = np.linspace(1, 10, 100, retstep=True)
print(arr_3)
print("Step size:", step)


[ 0.   2.5  5.   7.5 10. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8

ví dụ 3.3.2.3



In [1]:
# Ví dụ 3.3.2.3: Mảng con một chiều
import numpy as np

# Tạo mảng A gồm các số từ 0 đến 9
A = np.arange(10)
print("Mảng A:", A)

# 1️⃣ Lấy 5 phần tử đầu tiên của mảng A
print("A[:5]  -> 5 phần tử đầu tiên:", A[:5])

# 2️⃣ Lấy các phần tử ở sau vị trí thứ 5
print("A[5:]  -> Các phần tử sau vị trí 5:", A[5:])

# 3️⃣ Lấy các phần tử ở vị trí từ thứ 5 đến thứ 7 (chỉ số 4 đến 6)
print("A[4:7] -> Các phần tử từ vị trí 4 đến 6:", A[4:7])


Mảng A: [0 1 2 3 4 5 6 7 8 9]
A[:5]  -> 5 phần tử đầu tiên: [0 1 2 3 4]
A[5:]  -> Các phần tử sau vị trí 5: [5 6 7 8 9]
A[4:7] -> Các phần tử từ vị trí 4 đến 6: [4 5 6]


ví dụ 3.3.2.4

In [2]:
# Ví dụ 3.3.2.4: Mảng con hai chiều
import numpy as np

# Tạo mảng 2 chiều B (3 hàng, 4 cột)
B = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 0, 1, 2]
])

print("Mảng B:\n", B)

# 1️⃣ Lấy 2 hàng đầu tiên và 3 cột đầu tiên
print("\nB[:2, :3]  -> Hai hàng, ba cột:")
print(B[:2, :3])
# Giải thích:
# [:2] nghĩa là lấy hàng chỉ số 0 và 1
# [:3] nghĩa là lấy cột chỉ số 0, 1, 2

# 2️⃣ Lấy tất cả 3 hàng đầu tiên, các cột cách nhau 2 bước
print("\nB[:3, ::2] -> Ba hàng, cột bước nhảy là 2:")
print(B[:3, ::2])
# Giải thích:
# [:3]  nghĩa là hàng chỉ số 0,1,2
# [::2] nghĩa là cột 0, 2 (bỏ qua mỗi 1 cột)

# 3️⃣ Đảo ngược cả hàng và cột
print("\nB[::-1, ::-1] -> Đảo ngược hàng và cột:")
print(B[::-1, ::-1])
# Giải thích:
# [::-1] ở phần hàng -> lấy từ hàng cuối lên đầu
# [::-1] ở phần cột -> lấy từ cột cuối sang trái


Mảng B:
 [[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

B[:2, :3]  -> Hai hàng, ba cột:
[[1 2 3]
 [5 6 7]]

B[:3, ::2] -> Ba hàng, cột bước nhảy là 2:
[[1 3]
 [5 7]
 [9 1]]

B[::-1, ::-1] -> Đảo ngược hàng và cột:
[[2 1 0 9]
 [8 7 6 5]
 [4 3 2 1]]


In [1]:
# ==========================
# 3.3.2.3. MẢNG CON MỘT CHIỀU
# ==========================
import numpy as np

A = np.arange(10)
print("Mảng A:", A)

print("5 phần tử đầu tiên của A:", A[:5])
print("Các phần tử sau vị trí 5:", A[5:])
print("Các phần tử từ vị trí 4 đến 6:", A[4:7])

# ==========================
# 3.3.2.4. MẢNG CON ĐA CHIỀU
# ==========================
B = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,0,1,2]])
print("\nMảng B:\n", B)

print("Hai dòng, ba cột:\n", B[:2, :3])
print("Lấy các hàng từ 0-2, cột cách 2:\n", B[:3, ::2])
print("Đảo ngược hàng và cột:\n", B[::-1, ::-1])

# ==========================
# 3.3.2.5. TRUY CẬP HÀNG VÀ CỘT
# ==========================
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("\nMảng arr:\n", arr)

print("Cột đầu tiên:", arr[:, 0])
print("Hàng đầu tiên:", arr[0, :])
print("Hàng đầu tiên (cách khác):", arr[0])

# ==========================
# 3.3.3. VIEW VÀ SAO CHÉP MẢNG
# ==========================
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# Tạo view không sao chép
arr_view = arr_2d[:2, :2].view()
print("\nView arr_view:\n", arr_view)

# Thay đổi giá trị trong view
arr_view[0,0] = 100
print("View sau khi sửa:\n", arr_view)
print("Mảng gốc bị ảnh hưởng:\n", arr_2d)

# Slicing thông thường cũng tạo view
sub_arr = arr_2d[:2, :2]
sub_arr[0,0] = 10
print("\nsub_arr sau khi sửa:\n", sub_arr)
print("arr_2d bị thay đổi:\n", arr_2d)

# Sao chép mảng
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
sub_arr_copy = arr[:2, :2].copy()
sub_arr_copy[0,0] = 10
print("\nMảng copy:\n", sub_arr_copy)
print("Mảng gốc không bị ảnh hưởng:\n", arr)

# ==========================
# 3.3.3.4–3.3.3.5. ĐỊNH HÌNH LẠI MẢNG (RESHAPE)
# ==========================
arr = np.arange(1, 10)
grid = arr.reshape((3,3))
print("\nMảng reshape 3x3:\n", grid)

x = np.array([1, 2, 3])
print("Tạo ma trận hàng:", x.reshape((1, 3)))
print("Tạo ma trận hàng (newaxis):", x[np.newaxis, :])
print("Tạo ma trận cột:", x.reshape((3, 1)))
print("Tạo ma trận cột (newaxis):", x[:, np.newaxis])

# ==========================
# 3.3.4. KẾT HỢP VÀ CHIA TÁCH MẢNG
# ==========================
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("\nNối x, y:", np.concatenate([x, y]))

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print("\nNối theo trục dọc:\n", np.concatenate((a, b)))
print("Nối theo trục ngang:\n", np.concatenate((a, b), axis=1))

# vstack và hstack
print("\nKết hợp dọc bằng vstack:\n", np.vstack((a, b)))
print("Kết hợp ngang bằng hstack:\n", np.hstack((a, b)))

# Chia mảng 1 chiều
arr = np.arange(10)
sub_arr1 = np.split(arr, [3, 6])
sub_arr2 = np.split(arr, 2)
print("\nChia theo chỉ mục [3,6]:", sub_arr1)
print("Chia làm 2 phần:", sub_arr2)

# Chia mảng 2 chiều
arr = np.arange(16).reshape((4,4))
print("\nMảng 4x4:\n", arr)

upper, lower = np.vsplit(arr, 2)
print("Tách theo trục ngang:\n", upper, "\n", lower)

left, right = np.hsplit(arr, 2)
print("Tách theo trục dọc:\n", left, "\n", right)

# ==========================
# 3.3.5. THÊM, SỬA, XÓA PHẦN TỬ
# ==========================
arr = np.array([1,2,3])
new_arr = np.append(arr, 4)
print("\nappend:", new_arr)

# insert 1 chiều
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.insert(arr, 2, 10)
print("insert 1D:", new_arr)

# insert 2 chiều
arr_2d = np.array([[1,2],[3,4],[5,6]])
new_arr_2d = np.insert(arr_2d, 1, [7,8], axis=0)
print("insert 2D:\n", new_arr_2d)

# ==========================
# 3.3.6. TÌM KIẾM & SẮP XẾP
# ==========================
arr = np.array([1, 2, 3, 4, 5])
indices_where = np.where(arr == 3)
print("\nnp.where:", indices_where)

indices_argwhere = np.argwhere(arr == 3)
print("np.argwhere:\n", indices_argwhere)

arr = np.array([1, 5, 2, 3, 4])
print("Vị trí max:", np.argmax(arr))
print("Vị trí min:", np.argmin(arr))

# Sắp xếp
arr = np.array([5, 3, 1, 4, 2])
print("\nnp.sort:", np.sort(arr))
arr.sort()
print("Phương thức sort():", arr)


Mảng A: [0 1 2 3 4 5 6 7 8 9]
5 phần tử đầu tiên của A: [0 1 2 3 4]
Các phần tử sau vị trí 5: [5 6 7 8 9]
Các phần tử từ vị trí 4 đến 6: [4 5 6]

Mảng B:
 [[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]
Hai dòng, ba cột:
 [[1 2 3]
 [5 6 7]]
Lấy các hàng từ 0-2, cột cách 2:
 [[1 3]
 [5 7]
 [9 1]]
Đảo ngược hàng và cột:
 [[2 1 0 9]
 [8 7 6 5]
 [4 3 2 1]]

Mảng arr:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Cột đầu tiên: [1 4 7]
Hàng đầu tiên: [1 2 3]
Hàng đầu tiên (cách khác): [1 2 3]

View arr_view:
 [[1 2]
 [4 5]]
View sau khi sửa:
 [[100   2]
 [  4   5]]
Mảng gốc bị ảnh hưởng:
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]

sub_arr sau khi sửa:
 [[10  2]
 [ 4  5]]
arr_2d bị thay đổi:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]

Mảng copy:
 [[10  2]
 [ 4  5]]
Mảng gốc không bị ảnh hưởng:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Mảng reshape 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tạo ma trận hàng: [[1 2 3]]
Tạo ma trận hàng (newaxis): [[1 2 3]]
Tạo ma trận cột: [[1]
 [2]
 [3]]
Tạo ma trận cột (newaxis): [[1]
 [2]
 [3]]

Nối x, y: [1 2

ví dụ 4.4.3

In [1]:
import numpy as np

# Tạo mảng 1 chiều [0, 1, 2]
arr1 = np.arange(3)

# Tạo mảng 2 chiều (dạng cột)
arr2 = np.arange(3)[:, np.newaxis]

# In ra hai mảng
print("arr1 =")
print(arr1)
print("\narr2 =")
print(arr2)

# Cộng hai mảng với nhau (broadcasting)
result = arr1 + arr2

# In kết quả
print("\nKết quả arr1 + arr2 =")
print(result)


arr1 =
[0 1 2]

arr2 =
[[0]
 [1]
 [2]]

Kết quả arr1 + arr2 =
[[0 1 2]
 [1 2 3]
 [2 3 4]]


ví dụ 4.3.1.1

In [2]:
import numpy as np

# Tạo mảng dữ liệu với kích thước lớn (1000 phần tử, giá trị ngẫu nhiên từ 100–199)
data = np.random.randint(100, 200, size=1000)

# Tính giá trị trung bình của dữ liệu
mean_value = np.array([data.mean()])

# Tính tỷ lệ phần trăm tăng trưởng so với giá trị trung bình
percentage_growth = (data - mean_value) / mean_value * 100

# In ra 10 phần tử đầu tiên của mảng dữ liệu và tỷ lệ tăng trưởng tương ứng
print("Dữ liệu gốc:", data[:10])
print("Tỷ lệ phần trăm tăng trưởng:", percentage_growth[:10])


Dữ liệu gốc: [172 176 126 137 132 135 117 178 162 189]
Tỷ lệ phần trăm tăng trưởng: [ 14.41190948  17.07265156 -16.18662445  -8.86958373 -12.19551133
 -10.19995477 -22.17329413  18.4030226    7.76005428  25.72006333]


In [3]:
import numpy as np

# Tạo mảng 1 chiều
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Truy xuất các phần tử bằng một danh sách chỉ mục
indices = [1, 3, 4]
sub_arr_1 = arr[indices]

# In kết quả
print(sub_arr_1)


[20 40 50]
